# Copyright (C) 2019 Micron Technology.  All rights reserved.
# Workload: MongoDB YCSB, all workloads, load and run phase

api_version: 1

kvs.MainKvs:
  value_compression: lz4
  pfx_len: 9

kvs.UniqIdxKvs:
  cn_cursor_vra: 0
  pfx_len: 10
