# Copyright (C) 2019 Micron Technology.  All rights reserved.
# Workload: MongoDB Sysbench

api_version: 1

kvs.MainKvs:
  value_compression: none
  pfx_len: 9

kvs.UniqIdxKvs:
  pfx_len: 5

kvs.StdIdxKvs:
  pfx_len: 0
