# Copyright (C) 2019 Micron Technology.  All rights reserved.
# Workload: MongoDB IMP

api_version: 1

kvs.MainKvs:
  value_compression: lz4
  pfx_len: 10

kvs.UniqIdxKvs:
  cn_cursor_vra: 0
  pfx_len: 25
