# Copyright (C) 2019 Micron Technology.  All rights reserved.
# Workload: MongoDB YCSB, with media classes, all workloads, run phase

api_version: 1

kvs:
  mclass_policy: staging_max_capacity

kvs.MainKvs:
  value_compression: lz4
  pfx_len: 9

kvs.UniqIdxKvs:
  pfx_len: 10
