# Copyright (C) 2019 Micron Technology.  All rights reserved.
# Workload: Native YCSB, with media classes, workload E, load phase
#

api_version: 1
kvs:
  mclass_policy: staging_capacity_nofallback
  pfx_len: 7
