# Copyright (C) 2019 Micron Technology.  All rights reserved.
# Workload: Native YCSB, with media classes, workloads ABCDF, load phase

api_version: 1
kvs:
  mclass_policy: staging_max_capacity
  pfx_len: 7