# Copyright (C) 2019 Micron Technology.  All rights reserved.
# Workload: Native YCSB, with media classes, workload E, run phase
#
# The following parameters are experimental:
#   csched_vb_scatter_pct: percent of vblock scatter in leaf nodes
#   cn_cursor_vra: cursor vblock madvise-ahead in bytes

api_version: 1
kvdb:
  csched_vb_scatter_pct: 1
kvs:
  cn_cursor_vra: 0
  mclass_policy: staging_max_capacity
  pfx_len: 7
